# Serwery są dostępne prywatnie przez VPN.
[helpdesk]
helpdesk01 ansible_host=10.10.1.4
helpdesk02 ansible_host=10.10.1.5

# Wspólne ustawienia połączenia SSH.
[helpdesk:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3