---
- name: Configure HelpDesk Servers
  hosts: helpdesk
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes